# Options
set -sg terminal-overrides ",*:RGB"
set -g escape-time 0
set -g mouse on
set -g renumber-windows on  # keep numbering sequential
set -g repeat-time 1000

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Theme: borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# Theme: status
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#I:#W"

# Theme: status(windows)
set -g window-status-format ""
set -g window-status-current-format ""
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# # Keybindings: wasd
# bind C-k select-pane -U
# bind C-h select-pane -L
# bind C-j select-pane -D
# bind C-l select-pane -R

bind -n -r M-W resize-pane -U
bind -n -r M-A resize-pane -L
bind -n -r M-S resize-pane -D
bind -n -r M-D resize-pane -R

# Keybindings: disable repeat for arrows
bind Up select-pane -U
bind Left select-pane -L
bind Down select-pane -D
bind Right select-pane -R

# Keybindings: split
bind -n M-h split-window -h
bind | split-window -h
bind -n M-v split-window -v
bind - split-window -v

# Keybindings: windows
bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

# Keybindings: other
bind f resize-pane -Z
bind q detach-client
bind e choose-window -Z

bind -n M-w select-pane -U
bind -n M-a select-pane -L
bind -n M-s select-pane -D
bind -n M-d select-pane -R
bind -n M-f resize-pane -Z
